(cl:defpackage ros_game-srv
  (:use )
  (:export
   "GETUSERSCORE"
   "<GETUSERSCORE-REQUEST>"
   "GETUSERSCORE-REQUEST"
   "<GETUSERSCORE-RESPONSE>"
   "GETUSERSCORE-RESPONSE"
   "SETGAMEDIFFICULTY"
   "<SETGAMEDIFFICULTY-REQUEST>"
   "SETGAMEDIFFICULTY-REQUEST"
   "<SETGAMEDIFFICULTY-RESPONSE>"
   "SETGAMEDIFFICULTY-RESPONSE"
  ))

