// Generated by gencpp from file ros_game/GetUserScoreRequest.msg
// DO NOT EDIT!


#ifndef ROS_GAME_MESSAGE_GETUSERSCOREREQUEST_H
#define ROS_GAME_MESSAGE_GETUSERSCOREREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_game
{
template <class ContainerAllocator>
struct GetUserScoreRequest_
{
  typedef GetUserScoreRequest_<ContainerAllocator> Type;

  GetUserScoreRequest_()
    : username()  {
    }
  GetUserScoreRequest_(const ContainerAllocator& _alloc)
    : username(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _username_type;
  _username_type username;





  typedef boost::shared_ptr< ::ros_game::GetUserScoreRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_game::GetUserScoreRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetUserScoreRequest_

typedef ::ros_game::GetUserScoreRequest_<std::allocator<void> > GetUserScoreRequest;

typedef boost::shared_ptr< ::ros_game::GetUserScoreRequest > GetUserScoreRequestPtr;
typedef boost::shared_ptr< ::ros_game::GetUserScoreRequest const> GetUserScoreRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_game::GetUserScoreRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_game::GetUserScoreRequest_<ContainerAllocator1> & lhs, const ::ros_game::GetUserScoreRequest_<ContainerAllocator2> & rhs)
{
  return lhs.username == rhs.username;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_game::GetUserScoreRequest_<ContainerAllocator1> & lhs, const ::ros_game::GetUserScoreRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_game

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_game::GetUserScoreRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_game::GetUserScoreRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_game::GetUserScoreRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6839c60033378e900ba73a23bfa5117";
  }

  static const char* value(const ::ros_game::GetUserScoreRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6839c60033378e9ULL;
  static const uint64_t static_value2 = 0x00ba73a23bfa5117ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_game/GetUserScoreRequest";
  }

  static const char* value(const ::ros_game::GetUserScoreRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string username\n"
;
  }

  static const char* value(const ::ros_game::GetUserScoreRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.username);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUserScoreRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_game::GetUserScoreRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_game::GetUserScoreRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "username: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.username);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GAME_MESSAGE_GETUSERSCOREREQUEST_H
