// Generated by gencpp from file ros_game/GetUserScore.msg
// DO NOT EDIT!


#ifndef ROS_GAME_MESSAGE_GETUSERSCORE_H
#define ROS_GAME_MESSAGE_GETUSERSCORE_H

#include <ros/service_traits.h>


#include <ros_game/GetUserScoreRequest.h>
#include <ros_game/GetUserScoreResponse.h>


namespace ros_game
{

struct GetUserScore
{

typedef GetUserScoreRequest Request;
typedef GetUserScoreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUserScore
} // namespace ros_game


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_game::GetUserScore > {
  static const char* value()
  {
    return "ce20595763f2770f6e27a12a2546995d";
  }

  static const char* value(const ::ros_game::GetUserScore&) { return value(); }
};

template<>
struct DataType< ::ros_game::GetUserScore > {
  static const char* value()
  {
    return "ros_game/GetUserScore";
  }

  static const char* value(const ::ros_game::GetUserScore&) { return value(); }
};


// service_traits::MD5Sum< ::ros_game::GetUserScoreRequest> should match
// service_traits::MD5Sum< ::ros_game::GetUserScore >
template<>
struct MD5Sum< ::ros_game::GetUserScoreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_game::GetUserScore >::value();
  }
  static const char* value(const ::ros_game::GetUserScoreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_game::GetUserScoreRequest> should match
// service_traits::DataType< ::ros_game::GetUserScore >
template<>
struct DataType< ::ros_game::GetUserScoreRequest>
{
  static const char* value()
  {
    return DataType< ::ros_game::GetUserScore >::value();
  }
  static const char* value(const ::ros_game::GetUserScoreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_game::GetUserScoreResponse> should match
// service_traits::MD5Sum< ::ros_game::GetUserScore >
template<>
struct MD5Sum< ::ros_game::GetUserScoreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_game::GetUserScore >::value();
  }
  static const char* value(const ::ros_game::GetUserScoreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_game::GetUserScoreResponse> should match
// service_traits::DataType< ::ros_game::GetUserScore >
template<>
struct DataType< ::ros_game::GetUserScoreResponse>
{
  static const char* value()
  {
    return DataType< ::ros_game::GetUserScore >::value();
  }
  static const char* value(const ::ros_game::GetUserScoreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GAME_MESSAGE_GETUSERSCORE_H
