// Generated by gencpp from file ros_game/SetGameDifficultyRequest.msg
// DO NOT EDIT!


#ifndef ROS_GAME_MESSAGE_SETGAMEDIFFICULTYREQUEST_H
#define ROS_GAME_MESSAGE_SETGAMEDIFFICULTYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_game
{
template <class ContainerAllocator>
struct SetGameDifficultyRequest_
{
  typedef SetGameDifficultyRequest_<ContainerAllocator> Type;

  SetGameDifficultyRequest_()
    : change_difficulty()  {
    }
  SetGameDifficultyRequest_(const ContainerAllocator& _alloc)
    : change_difficulty(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _change_difficulty_type;
  _change_difficulty_type change_difficulty;





  typedef boost::shared_ptr< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetGameDifficultyRequest_

typedef ::ros_game::SetGameDifficultyRequest_<std::allocator<void> > SetGameDifficultyRequest;

typedef boost::shared_ptr< ::ros_game::SetGameDifficultyRequest > SetGameDifficultyRequestPtr;
typedef boost::shared_ptr< ::ros_game::SetGameDifficultyRequest const> SetGameDifficultyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator1> & lhs, const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.change_difficulty == rhs.change_difficulty;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator1> & lhs, const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_game

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8a8d257ae7cf9a054243931c3dfd215";
  }

  static const char* value(const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8a8d257ae7cf9a0ULL;
  static const uint64_t static_value2 = 0x54243931c3dfd215ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_game/SetGameDifficultyRequest";
  }

  static const char* value(const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string change_difficulty\n"
;
  }

  static const char* value(const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.change_difficulty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGameDifficultyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_game::SetGameDifficultyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_game::SetGameDifficultyRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "change_difficulty: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.change_difficulty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_GAME_MESSAGE_SETGAMEDIFFICULTYREQUEST_H
