// Generated by gencpp from file ros_game/SetGameDifficulty.msg
// DO NOT EDIT!


#ifndef ROS_GAME_MESSAGE_SETGAMEDIFFICULTY_H
#define ROS_GAME_MESSAGE_SETGAMEDIFFICULTY_H

#include <ros/service_traits.h>


#include <ros_game/SetGameDifficultyRequest.h>
#include <ros_game/SetGameDifficultyResponse.h>


namespace ros_game
{

struct SetGameDifficulty
{

typedef SetGameDifficultyRequest Request;
typedef SetGameDifficultyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGameDifficulty
} // namespace ros_game


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_game::SetGameDifficulty > {
  static const char* value()
  {
    return "9d6c7c12eefb5ab4ae8ce42c4c512e6f";
  }

  static const char* value(const ::ros_game::SetGameDifficulty&) { return value(); }
};

template<>
struct DataType< ::ros_game::SetGameDifficulty > {
  static const char* value()
  {
    return "ros_game/SetGameDifficulty";
  }

  static const char* value(const ::ros_game::SetGameDifficulty&) { return value(); }
};


// service_traits::MD5Sum< ::ros_game::SetGameDifficultyRequest> should match
// service_traits::MD5Sum< ::ros_game::SetGameDifficulty >
template<>
struct MD5Sum< ::ros_game::SetGameDifficultyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_game::SetGameDifficulty >::value();
  }
  static const char* value(const ::ros_game::SetGameDifficultyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_game::SetGameDifficultyRequest> should match
// service_traits::DataType< ::ros_game::SetGameDifficulty >
template<>
struct DataType< ::ros_game::SetGameDifficultyRequest>
{
  static const char* value()
  {
    return DataType< ::ros_game::SetGameDifficulty >::value();
  }
  static const char* value(const ::ros_game::SetGameDifficultyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_game::SetGameDifficultyResponse> should match
// service_traits::MD5Sum< ::ros_game::SetGameDifficulty >
template<>
struct MD5Sum< ::ros_game::SetGameDifficultyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_game::SetGameDifficulty >::value();
  }
  static const char* value(const ::ros_game::SetGameDifficultyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_game::SetGameDifficultyResponse> should match
// service_traits::DataType< ::ros_game::SetGameDifficulty >
template<>
struct DataType< ::ros_game::SetGameDifficultyResponse>
{
  static const char* value()
  {
    return DataType< ::ros_game::SetGameDifficulty >::value();
  }
  static const char* value(const ::ros_game::SetGameDifficultyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_GAME_MESSAGE_SETGAMEDIFFICULTY_H
